// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionAndMove } from "./PositionAndMove";

export interface BestPos { pos: PositionAndMove | null, pos_list: Array<PositionAndMove>, deep_eval: number, }