// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FinishType = "Draw1" | "Draw2" | "Draw3" | "Draw4" | "Draw5" | "BlackWin" | "WhiteWin";