// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveItem } from "./MoveItem";
import type { Strike } from "./Strike";

export interface MoveList { list: Array<MoveItem>, current_chain: Strike, }