// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuietMove } from "./QuietMove";
import type { Strike } from "./Strike";

export interface MoveItem { strike: Strike | null, mov: QuietMove | null, }