// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorType } from "./ColorType";

export interface Piece { pos: number, color: ColorType, is_king: boolean, stricken: boolean, }