// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveItem } from "./MoveItem";
import type { Position } from "./Position";

export interface PositionAndMove { pos: Position, mov: MoveItem | null, }