// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StraightStrike { v: Array<number>, from: number, take: number, to: number, king_move: boolean, }