// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StraightStrike } from "./StraightStrike";

export interface Strike { vec: Array<StraightStrike>, king_move: boolean, }