// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Vector<T> { points: Array<T>, direction: number, range_a: number | null, range_b: number | null, }